site_name: Personal Wiki
site_url: https://chusovich.github.io/wiki

theme:
  icon:
    logo: material/library
  name: material
  palette: 
    # Set the primary color
    primary: blue
    accent: teal

    # Add additional search features
    features:
    - search.highlight
    - search.suggest
    - navigation.instant
    - navigation.tabs
    - content.code.copy

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  # Extensions for annotations
  - attr_list
  - md_in_html
  - pymdownx.superfences
  
  # Extensions for code syntax highlighting
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  
  # Extension for tables
  - tables
